### PR TITLE
A tooltip for admiral name

### PR DESCRIPTION
**Pull request by gakada**
This is an old commit (so probably should be re-tested), but it adds some extra information in a tooltip for admiral name.

### CODE REVIEW

**Comment by andanteyk** [comment]
I think it is a good function. Thank you for your contribution.
By the way, what does "exp:" mean? I could not think of the purpose of that function.

**Comment by gakada** [comment]
It is average experience per battle and average experience per win (just totals divided). It can indicate how much ranking one does, as it will be significantly higher when the majority of sorties is full 5-4 runs.

**Comment by andanteyk** [comment]
Merged at ee81cbaa15833789dd6b410f0dd74eb24bc42425. Thank you very much.
Slight modification was done at 4bfc0f72f703b10939715d348b07ebdbe9576559.

* Unified line feed code to `\r\n` which is used elsewhere.
* I made it different line for exp. This is because the tool tip was stretched sideways.
* (Although rare, but just in case) I added a code to avoid div/0 error.

**Comment by gakada** [comment]
ありがとうございます！

**Pull request closed without merging**
