### PR TITLE
Feature/battle detail

### PR DESCRIPTION
**Pull request by xiaozhikang0916**
Battle detail

Now it's able to view battle detailed information of each ship in Battle Form.
t5mu1 s 7mni d0e0b m u
tazu82z wg83x5if pz e r

It's suitable in normal fleet battle, night battle, and combined fleet battle.

This branch is checkout from `develop`, and there are bugs in showing battle information  of practice  in commit `戦闘：基地航空隊戦況表示を追加`  `844e869` , so it should be fixed before you want to see how it work in practice.

### CODE REVIEW

**Comment by andanteyk** [comment]
Thank you for your contribution.
I'll check it. Please wait a while.

I have also noticed bug about practice, and fixed it on local.
Thank you for your report.

**Comment by andanteyk** [comment]
I checked. It is a good feature. I would like to implement.
There are some point I want to modify and adjust.
I'll commit it later, please confirm.

**Comment by xiaozhikang0916** [comment]
Glad to hear that, waiting for your commits

**Comment by andanteyk** [comment]
I commited modified version at a07cbae5dd657e50b84b34899f619ef10fe9e95c.

Sorry for broken English. 
If you can read Japanese, please read its commit message.

* Refactoring and Formatting.
    * Rename, Indent, Spacing, etc.
* Change `BattleDetail`
    * Add Attacker/Defender as `ShipDataMaster` for calculating `AttackType`.
    * `BattleDescription()` is implemented on base class. 
        Duplicated code on derived classes was merged, difference between day and night is represented at new abstract methods.
    * enum `CutinType` is removed.
        String of AttackType( `砲撃`, `連続射撃`, etc. ) is already exist at `Constants.GetDay/NightAttackKind()`; Notation shaking is removed.
* Change Tooltip Format

```
《第一砲撃戦》
長門改 → 空母ヲ級 #2
[連続射撃] Miss , 112 Critical!
```

* 
    * Emphasis Title.
    * Merge AttackType and Damage into 1 line.
    * Changed "0 Miss" to "Miss".
    * Changed "連撃" to "連続射撃" (and some text). Notation shaking is removed.
* Fixed: Error at Combined Fleet - Long Distance Air Raid, Combined Fleet - Air Battle
* Fixed: On Combined Fleet - Opening Night Battle, Battle result of second fleet also shows on first fleet.
* FormBattle : merge duplicated codes.

**Comment by xiaozhikang0916** [comment]
I've checked your commit, thanks for refining the code.
You may notice that it doesn't the air battle information. I will push my commits merged with yours later, please check and confirm.
I'm OK with Japanese and you can just reply in Japanese (but i'm not skilled enough to write in it)

**Comment by xiaozhikang0916** [comment]
I have pushed my commits, but without fully test (especially in combined fleet situation).
You may check and test it.

---
And there are outputs in english words in my code, you should search `//TODO` in `BattleDetail.cs` and `FormBatle.cs` to find them.

**Comment by andanteyk** [comment]
I commited modified version at 0f1be346ed2b07ba3f9f2c4d3589cce9e575f8ec .
Mainly bugfix. Please check its commit message.

**Comment by xiaozhikang0916** [comment]
I have reviewed your code. It's OK for me. Waiting to see the feature in release version.

**Pull request merged**
