### PR TITLE
Improve StyleSheet Handling

### LINKED ISSUE #93: ブラウザ：アイテム購入画面が開けない
アイテムを購入しようとすると、購入確認画面が開かずそのまま閉じる

### PR DESCRIPTION
**Pull request by RadarNyan**
Should fix #93 

image
The purchasing page should look like this, I haven't test the entire purchasing process though.

Commit 58e8bd4 is not related to this matter but to fix a mistake I made in the last PR.

### CODE REVIEW

**Comment by andanteyk** [comment]
購入確認画面までは正常に表示されることを確認しました。
しかし、実際にアイテムを購入したところ、正常にアイテム画面に戻らず(この修正が行われる前にアイテムを購入しようとした時と同様の表示になる)、購入アイテムが反映されない問題が発生しました。
購入自体は成功しており、再ログインすると正常に表示されるようになります。

I confirmed that the purchase confirmation screen will be displayed properly.
However, when I purchased the item, it did not return to the item screen correctly (it appears the same as when trying to purchase the item before this correction is done), the purchased item was not reflected.
The purchase has been successful, and will be displayed properly when logging in again.

**Comment by RadarNyan** [comment]
image
So I tried to purchase something, it worked as expected. Are you sure your problem is caused by 74EO?

**Comment by andanteyk** [comment]
設定を初期化してもう一度試してみましたが、購入後にこの画面で停止します。
ほかに原因がある可能性についても調査中です。

I initialized settings and tried it again, but it will stop on this screen after purchase.
I am also investigating the possibility of other causes.

**Comment by RadarNyan** [comment]
I've made more changes, now it's possible to switch StyleSheet on/off on-the-fly via option in Browser toolbar menu.

Again, commit 917ca36 is not related to this matter but to fix this problem: https://github.com/RadarNyan/ElectronicObserver/issues/9

**Comment by andanteyk** [comment]
追加されたコミットを加えてアイテム購入を再度試したところ、正常な動作を確認できました。
スタイルシートのスイッチ機能は良いですね。ありがとうございます。

Included added commit and tried item purchase again, then I confirmed it works properly.
Style-sheet switching function is good. Thank you.

**Pull request merged**
