### PR TITLE
Fix CRLF issue

### PR DESCRIPTION
**Pull request by RadarNyan**
There are files with mixed line endings (LF & CRLF) in repository (eg: "ElectronicObserver\Window\Dialog\DialogConfiguration.Designer.cs") causing problem while editing them with an editor that normalize line ending. This commit will modify all the files using CRLF or mixed line endings to using LF only, like any other files in the repository.

Maybe you wanna check your **core.autocrlf** setting :)

---

BTW, I just followed the guide here: http://stackoverflow.com/questions/1510798/trying-to-fix-line-endings-with-git-filter-branch-but-having-no-luck/1511273#1511273 The only difference was, I had to use -f switch on "git add" part or I'll have a file deleted in commit.

You may want to do this yourself so you don't have to check all the 74 files to make sure I didn't make any mistake, I'm not very so skilled with GitHub or git anyway (you can see I made a incorrect PR last time)

### CODE REVIEW

**Comment by andanteyk** [comment]
Thank you for your cooperation. I did not notice it.
I am working on the implementation of battle with enemy combined fleet now.
I will check it after that it is completed. Please wait for a while.

In this repository, I think CRLF is a major new line code.
Why did you change it to LF, not CRLF? Please let us know if there is a reason.

**Comment by RadarNyan** [comment]
Well, by default (core.autocrlf = true) git on Windows will convert all line endings to LF when commit, that's what I see in this repo - LF is the major since this commit only changed 74 files, I believe there're way more files than that in this repo, I could be wrong though.

In theory, git should be able to convert all LF back to CRLF when I pull from Windows client, but it just somehow failed on those files with mixed LF&CRLF line endings on my PC, for example in this file:  
https://github.com/andanteyk/ElectronicObserver/blob/master/ElectronicObserver/Window/Dialog/DialogConfiguration.Designer.cs  
it started off with LF and changed to CRLF from line 26, back to LF from line 2520.

I'm not against using CRLF as the line ending since it's a Windows project anyway, but just don't mix them in a single file, that would cause trouble - I just tried to localize one line in a file then two blocks of codes I didn't even touch are marked as changed by git, and that's the first time I've discovered there's a problem with line endings.

**Comment by andanteyk** [comment]
I re-checked it by "download zip"; certainly there are more LF than CRLF.
Sorry for misunderstanding...

I'll merge it after current work is completed. Thank you.

***

I checked my `core.autocrlf`, it is `true`.
I do not know where to got mixed...

**Comment by andanteyk** [comment]
This problem is maybe fixed at https://github.com/andanteyk/ElectronicObserver/tree/RadarNyan-PR-patch-CRLF ; Could you confirm it?
I am not confident about my operation...

**Comment by RadarNyan** [comment]
Since you've added more code, I really wouldn't recommend to merge this PR right now. I think it's better if you finish your work, merge it to your develop branch, and fix CRLF issue last to avoid conflict when you try to merge your working branch.

Here's a quick guide on how to make this commit:
1. First, commit everything so your working tree is clean.
2. Now use the following commands in git shell (slightly modified from the link provided above, this is what I did to create this PR.)
```
git rm --cached -r .
git config core.autocrlf true
git diff --cached --name-only -z | xargs -0 git add -f
git commit -m "Fixed CRLF Issue"
```
Or, I can update this PR if you wish.
Just commit everything to develop branch and send me a reply, then I'll rebase and update this PR :)

**Comment by andanteyk** [comment]
I would appreciate it if you could update this PR...

**Comment by RadarNyan** [comment]
I have no idea what I've done caused this PR to close...

**Comment by andanteyk** [comment]
Thank you very much for your support!

**Pull request merged**
